delete from stock;
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('Adani Ports and Special Economic Zone Ltd.','SERVICES','ADANIPORTS','EQ','INE742F01042',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('Asian Paints Ltd.','CONSUMER GOODS','ASIANPAINT','EQ','INE021A01026',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('Axis Bank Ltd.','FINANCIAL SERVICES','AXISBANK','EQ','INE238A01034',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('Bajaj Auto Ltd.','AUTOMOBILE','BAJAJ-AUTO','EQ','INE917I01010',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('Bajaj Finance Ltd.','FINANCIAL SERVICES','BAJFINANCE','EQ','INE296A01024',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('Bajaj Finserv Ltd.','FINANCIAL SERVICES','BAJAJFINSV','EQ','INE918I01018',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('Bharat Petroleum Corporation Ltd.','ENERGY','BPCL','EQ','INE029A01011',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('Bharti Airtel Ltd.','TELECOM','BHARTIARTL','EQ','INE397D01024',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('Bharti Infratel Ltd.','TELECOM','INFRATEL','EQ','INE121J01017',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('Britannia Industries Ltd.','CONSUMER GOODS','BRITANNIA','EQ','INE216A01030',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('Cipla Ltd.','PHARMA','CIPLA','EQ','INE059A01026',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('Coal India Ltd.','METALS','COALINDIA','EQ','INE522F01014',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('Dr. Reddy\'s Laboratories Ltd.','PHARMA','DRREDDY','EQ','INE089A01023',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('Eicher Motors Ltd.','AUTOMOBILE','EICHERMOT','EQ','INE066A01013',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('GAIL (India) Ltd.','ENERGY','GAIL','EQ','INE129A01019',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('Grasim Industries Ltd.','CEMENT & CEMENT PRODUCTS','GRASIM','EQ','INE047A01021',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('HCL Technologies Ltd.','IT','HCLTECH','EQ','INE860A01027',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('HDFC Bank Ltd.','FINANCIAL SERVICES','HDFCBANK','EQ','INE040A01026',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('Hero MotoCorp Ltd.','AUTOMOBILE','HEROMOTOCO','EQ','INE158A01026',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('Hindalco Industries Ltd.','METALS','HINDALCO','EQ','INE038A01020',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('Hindustan Unilever Ltd.','CONSUMER GOODS','HINDUNILVR','EQ','INE030A01027',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('Housing Development Finance Corporation Ltd.','FINANCIAL SERVICES','HDFC','EQ','INE001A01036',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('ICICI Bank Ltd.','FINANCIAL SERVICES','ICICIBANK','EQ','INE090A01021',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('ITC Ltd.','CONSUMER GOODS','ITC','EQ','INE154A01025',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('Indiabulls Housing Finance Ltd.','FINANCIAL SERVICES','IBULHSGFIN','EQ','INE148I01020',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('Indian Oil Corporation Ltd.','ENERGY','IOC','EQ','INE242A01010',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('IndusInd Bank Ltd.','FINANCIAL SERVICES','INDUSINDBK','EQ','INE095A01012',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('Infosys Ltd.','IT','INFY','EQ','INE009A01021',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('JSW Steel Ltd.','METALS','JSWSTEEL','EQ','INE019A01038',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('Kotak Mahindra Bank Ltd.','FINANCIAL SERVICES','KOTAKBANK','EQ','INE237A01028',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('Larsen & Toubro Ltd.','CONSTRUCTION','LT','EQ','INE018A01030',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('Mahindra & Mahindra Ltd.','AUTOMOBILE','M&M','EQ','INE101A01026',b'0');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('Maruti Suzuki India Ltd.','AUTOMOBILE','MARUTI','EQ','INE585B01010',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('NTPC Ltd.','ENERGY','NTPC','EQ','INE733E01010',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('Oil & Natural Gas Corporation Ltd.','ENERGY','ONGC','EQ','INE213A01029',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('Power Grid Corporation of India Ltd.','ENERGY','POWERGRID','EQ','INE752E01010',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('Reliance Industries Ltd.','ENERGY','RELIANCE','EQ','INE002A01018',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('State Bank of India','FINANCIAL SERVICES','SBIN','EQ','INE062A01020',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('Sun Pharmaceutical Industries Ltd.','PHARMA','SUNPHARMA','EQ','INE044A01036',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('Tata Consultancy Services Ltd.','IT','TCS','EQ','INE467B01029',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('Tata Motors Ltd.','AUTOMOBILE','TATAMOTORS','EQ','INE155A01022',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('Tata Steel Ltd.','METALS','TATASTEEL','EQ','INE081A01012',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('Tech Mahindra Ltd.','IT','TECHM','EQ','INE669C01036',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('Titan Company Ltd.','CONSUMER GOODS','TITAN','EQ','INE280A01028',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('UPL Ltd.','FERTILISERS & PESTICIDES','UPL','EQ','INE628A01036',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('UltraTech Cement Ltd.','CEMENT & CEMENT PRODUCTS','ULTRACEMCO','EQ','INE481G01011',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('Vedanta Ltd.','METALS','VEDL','EQ','INE205A01025',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('Wipro Ltd.','IT','WIPRO','EQ','INE075A01022',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('Yes Bank Ltd.','FINANCIAL SERVICES','YESBANK','EQ','INE528G01027',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('Zee Entertainment Enterprises Ltd.','MEDIA & ENTERTAINMENT','ZEEL','EQ','INE256A01028',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('ABB India Ltd.','INDUSTRIAL MANUFACTURING','ABB','EQ','INE117A01022',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('ACC Ltd.','CEMENT & CEMENT PRODUCTS','ACC','EQ','INE012A01025',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('Ambuja Cements Ltd.','CEMENT & CEMENT PRODUCTS','AMBUJACEM','EQ','INE079A01024',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('Ashok Leyland Ltd.','AUTOMOBILE','ASHOKLEY','EQ','INE208A01029',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('Aurobindo Pharma Ltd.','PHARMA','AUROPHARMA','EQ','INE406A01037',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('Avenue Supermarts Ltd.','CONSUMER GOODS','DMART','EQ','INE192R01011',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('Bajaj Holdings & Investment Ltd.','FINANCIAL SERVICES','BAJAJHLDNG','EQ','INE118A01012',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('Bandhan Bank Ltd.','FINANCIAL SERVICES','BANDHANBNK','EQ','INE545U01014',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('Bank of Baroda','FINANCIAL SERVICES','BANKBARODA','EQ','INE028A01039',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('Bharat Heavy Electricals Ltd.','INDUSTRIAL MANUFACTURING','BHEL','EQ','INE257A01026',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('Biocon Ltd.','PHARMA','BIOCON','EQ','INE376G01013',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('Bosch Ltd.','AUTOMOBILE','BOSCHLTD','EQ','INE323A01026',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('Cadila Healthcare Ltd.','PHARMA','CADILAHC','EQ','INE010B01027',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('Colgate Palmolive (India) Ltd.','CONSUMER GOODS','COLPAL','EQ','INE259A01022',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('Container Corporation of India Ltd.','SERVICES','CONCOR','EQ','INE111A01025',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('DLF Ltd.','CONSTRUCTION','DLF','EQ','INE271C01023',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('Dabur India Ltd.','CONSUMER GOODS','DABUR','EQ','INE016A01026',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('Divi\'s Laboratories Ltd.','PHARMA','DIVISLAB','EQ','INE361B01024',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('General Insurance Corporation of India','FINANCIAL SERVICES','GICRE','EQ','INE481Y01014',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('Godrej Consumer Products Ltd.','CONSUMER GOODS','GODREJCP','EQ','INE102D01028',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('HDFC Asset Management Company Ltd.','FINANCIAL SERVICES','HDFCAMC','EQ','INE127D01025',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('HDFC Life Insurance Company Ltd.','FINANCIAL SERVICES','HDFCLIFE','EQ','INE795G01014',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('Havells India Ltd.','CONSUMER GOODS','HAVELLS','EQ','INE176B01034',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('Hindustan Petroleum Corporation Ltd.','ENERGY','HINDPETRO','EQ','INE094A01015',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('Hindustan Zinc Ltd.','METALS','HINDZINC','EQ','INE267A01025',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('ICICI Lombard General Insurance Company Ltd.','FINANCIAL SERVICES','ICICIGI','EQ','INE765G01017',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('ICICI Prudential Life Insurance Company Ltd.','FINANCIAL SERVICES','ICICIPRULI','EQ','INE726G01019',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('InterGlobe Aviation Ltd.','SERVICES','INDIGO','EQ','INE646L01027',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('L&T Finance Holdings Ltd.','FINANCIAL SERVICES','L&TFH','EQ','INE498L01015',b'0');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('Lupin Ltd.','PHARMA','LUPIN','EQ','INE326A01037',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('MRF Ltd.','AUTOMOBILE','MRF','EQ','INE883A01011',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('Marico Ltd.','CONSUMER GOODS','MARICO','EQ','INE196A01026',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('Motherson Sumi Systems Ltd.','AUTOMOBILE','MOTHERSUMI','EQ','INE775A01035',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('NHPC Ltd.','ENERGY','NHPC','EQ','INE848E01016',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('NMDC Ltd.','METALS','NMDC','EQ','INE584A01023',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('Oracle Financial Services Software Ltd.','IT','OFSS','EQ','INE881D01027',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('Page Industries Ltd.','TEXTILES','PAGEIND','EQ','INE761H01022',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('Petronet LNG Ltd.','ENERGY','PETRONET','EQ','INE347G01014',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('Pidilite Industries Ltd.','CHEMICALS','PIDILITIND','EQ','INE318A01026',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('Piramal Enterprises Ltd.','PHARMA','PEL','EQ','INE140A01024',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('Procter & Gamble Hygiene & Health Care Ltd.','CONSUMER GOODS','PGHH','EQ','INE179A01014',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('SBI Life Insurance Company Ltd.','FINANCIAL SERVICES','SBILIFE','EQ','INE123W01016',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('Shree Cement Ltd.','CEMENT & CEMENT PRODUCTS','SHREECEM','EQ','INE070A01015',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('Shriram Transport Finance Co. Ltd.','FINANCIAL SERVICES','SRTRANSFIN','EQ','INE721A01013',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('Siemens Ltd.','INDUSTRIAL MANUFACTURING','SIEMENS','EQ','INE003A01024',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('Steel Authority of India Ltd.','METALS','SAIL','EQ','INE114A01011',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('The New India Assurance Company Ltd.','FINANCIAL SERVICES','NIACL','EQ','INE470Y01017',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('United Breweries Ltd.','CONSUMER GOODS','UBL','EQ','INE686F01025',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('United Spirits Ltd.','CONSUMER GOODS','MCDOWELL-N','EQ','INE854D01024',b'1');
insert into stock(company_name, industry, symbol, series, isin_code,is_active) values ('Vodafone Idea Ltd.','TELECOM','IDEA','EQ','INE669E01016',b'1');
commit;
